name: config
root: ~/.config

windows:
  - main:
      root: ~/.config
      panes:

  - qmk:
      root: ~/.config/qmk
      panes:

  - nvim:
      root: ~/.config/nvim
      panes:
        -

  - pack:
      root: ~/.local/share/nvim/site/pack
      panes:
        -

  - fish:
      root: ~/.config/fish
      panes:
        -

  - tmux:
      root: ~/.config/tmux
      panes:
        -

  - tx:
      root: ~/.config/tmuxinator
      panes:
        -

