#!/bin/bash

tmux new -s "IDE" -d                # Create tmux session named "IDE" and detach the session
#-----------------------------------# do prefix-q   -> to get pane number
tmux split-window -v -p 20          # pane number -> 0 |
tmux split-window -h -p 66          # pane number -> 3 | -> they're in same window
tmux split-window -h -p 50          # pane number -> 2 |
#-----------------------------------# the reset is pane number -> 1
tmux select-pane -U                 # go (Up) to select window number -> 0
tmux send-keys -t "IDE" 'nvim' C-m  # target(-t) "IDE" session & run 'nvim',the (C-m) is <CR>
#-----------------------------------#
tmux select-pane -D -t 2 -L         # select window(3) by go down and go left two(2) window where window(1)
#-----------------------------------#
tmux attach-session -d -t IDE       # run tmux and then attach and target(-t) the 'IDE' session.














