-- Load coifguration files
require("options")
require("keymaps")
require("autocmd")
require("plugins")
--require("codex.alpha")
require("codex.themes")
require("codex.lualine")
require("codex.bufferline")
require("codex.neo-tree")
require("codex.telescope")
require("codex.vim-illuminate")
require("codex.colorizer")
require("codex.treesitter")
require("codex.lsp")
require("codex.cmp")
require("codex.hlchunk")
require("codex.gitsigns")
require("codex.web-devicons")
require("codex.comment")
require("codex.nvim_surround")
require("codex.lsp_signature")
require("codex.lspsaga")
-- uncomment this block if you install them
--[[ require("codex.notify")
require("codex.noice") ]]
